SET(GAME_SRCS 
    backend/ugdktiledfileloader.cc 
    backend/ugdktiledfileloader.h 
    frontend/debugtools.cc 
    frontend/debugtools.h 
    frontend/frontend.cc 
    frontend/frontend.h 
    frontend/main.cc 
    frontend/nativebuilders.h 
    frontend/nativebuilders/gameviewerscene.cc 
    frontend/nativebuilders/maprenderer.cc 
    frontend/nativebuilders/maprenderer.h 
    frontend/nativebuilders/playercharacter.cc 
    frontend/nativebuilders/playercharacter.h 
    frontend/scenes/console.cc 
    frontend/scenes/console.h 
    frontend/serverproxy.cc 
    frontend/serverproxy.h 
    server/platformingcore.cc 
    server/platformingcore.h 
)
