SET(GAME_SRCS 
    frontend/debugtools.cc 
    frontend/debugtools.h 
    frontend/frontend.cc 
    frontend/frontend.h 
    frontend/main.cc 
    frontend/nativebuilders.h 
    frontend/nativebuilders/gamescene.cc 
    frontend/scenes/console.cc 
    frontend/scenes/console.h 
    server/platformingcore.cc 
    server/platformingcore.h 
    shared/tiled/layer.cc 
    shared/tiled/layer.h 
    shared/tiled/map.cc 
    shared/tiled/map.h 
    shared/tiled/object.cc 
    shared/tiled/object.h 
    shared/tiled/tileset.cc 
    shared/tiled/tileset.h 
)
